config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'
  get 'aboutUs', to: 'homes#about_us', as: 'about_us'
  get 'services', to: 'homes#services', as: 'services'
  get 'work', to: 'homes#work', as: 'work'
  get 'sitemap', to: 'homes#sitemap', as: 'sitemap'
  get 'career', to: 'homes#career', as: 'career'

  resources :posts do
  	resources :comments
  end
  
  get 'contact', to: 'contacts#new', as: 'contact'
  post 'contact', to: 'contacts#create'
  post 'message', to: 'contacts#message'

%w( 404 422 500 ).each do |code|
  get code, :to => "errors#show", :code => code
end


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	scope :recent_comment, -> { order('created_at DESC').limit(5) }
end

app/models/contact.rb
class Contact < ApplicationRecord
 
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :banner_image, BannerImageUploader
	has_many :comments, dependent: :destroy
  extend FriendlyId
  friendly_id :title, use: :slugged
  scope :recent_post, -> { order('created_at DESC').limit(5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post, only: [:new, :create]

	def create
		@comment = @post.comments.new(comment_params)
		if @comment.save
		 	redirect_to post_path(@post)
		else
			redirect_to root_path
		end
	end

	protected
	def comment_params
	  params.require(:comment).permit(:message, :name, :email, :post_id)
	end

	def set_post
		@post = Post.friendly.find(params[:post_id])
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)
		if @contact.save
			redirect_to root_path
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
      ContactMailer.new_contact(@contact).deliver_now
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
	end

	# def message	
	# 	ContactMailer.new_contact(@contact).deliver_now
	# end

	protected
	def contact_params
		params.require(:contact).permit(:name, :email, :message)
	end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
   layout false
   def show
    render status_code.to_s, :status => status_code
  end
 
  protected
 
  def status_code
    params[:code] || 500
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index; end

	def about_us; end

	def services; end

	def work; end

	def sitemap; end

	def career; end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
		@posts = @posts.paginate(page:  params[:page], per_page:  6)
	end

	def show
		@post = Post.friendly.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def active_class(link_path)
  	current_page?(link_path) ? "active" : ""
  end
end

app/helpers/posts_helper.rb
module PostsHelper
	# def post_image post
 #    if post.image.present?
 #      image_tag post.image_url :thumbnail
 #    else
 #      image_tag 'default.jpg'
 #    end
 #  end
end

app/views/comments/_form.html.erb
<div class="col-md-6 comment-form">
<h5 class="mt-0">Leave Comment:</h5>
<%= form_for [@post,  @post.comments.new] do |f| %>
  <div class="form-group">
	<%= f.label :comments %>
	<%= f.text_area :message, class: "form-control", rows: "3", required: :true %><br>
  </div>
  <div class="form-group">
   <%= f.label :name %>
   <%= f.text_field :name, class: "form-control", required: :true %><br>
   </div>
   <div class="form-group">
   <%= f.label :email %>
   <%= f.email_field :email, class: "form-control", required: :true %>
   </div>

    <div class="form-group">
	<%= f.submit "Submit", class: "btn btn-warning"%>
	</div>
<% end %>
</div>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/contacts/_mail_sent.html.erb
<h1>Mailsent</h1>

app/views/contacts/message.js.erb
$('.contact').replaceWith("<%=j render('mail_sent')%>");

app/views/contacts/new.html.erb
<section class="our-work-content">
  <div class="container">
    <div class="row">
    <h1 class="text-center">Contact Us</h1>
      <div class="col-md-6 col-sm-12">
        <div class="contact-form">
          
          <%= form_for(:contact, url: contact_path) do |f| %>
            <div class="row">
              <div class="comment-box"></div>
              <div class="col-md-6 form-group">
               <%= f.text_field :name, class: "form-control", placeholder: "Name", type:"text", required: :true%>
              </div> 
              <div class="col-md-6 form-group">
                <%= f.email_field :email, class: "form-control", placeholder: "Email", type:"text", required: :true%>
              </div>
              <label class="col-md-12 control-label" for="textarea"></label>

              <div class="col-md-12">
                <%= f.text_area :message, class: "form-control", id: "textarea", required: :true%>
              </div>
              <div class="col-md-8 text-left">
               <%= f.submit "send message", class: "btn btn btn-warning"%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-6 col-sm-12">
        <div class="contact-add-box">
          <ul class="address-details">
            <h3>Our Address</h3>
            <li><i class="glyphicon glyphicon-map-marker"></i> 303, HeyDay Technologies Mangal </li>
             <li class="address">Nagar Road Indore, Madhya Pradesh India.</li>
            <li><i class="fa fa-phone"></i>07314972670</li>
            <li><i class="glyphicon glyphicon-envelope"> </i>hello@heydaytechnologies.com</li>
          </ul>
        </div>
      </div>
  
    </div>
  </div>
</section>
<div class="map-frame">
      <div class="container-fliud">
        <div class="row">
          <div class="col-sm-12">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5205.905683894717!2d75.85696161259408!3d22.686158907633477!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3962fcf129c55555%3A0x1d900acb06ce2221!2sHeyDay+Technologies!5e0!3m2!1sen!2sin!4v1516713958495" width="100%  " height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
  </div>

app/views/homes/about_us.html.erb
<section class="about-middle"><!--about-middle start -->
	<div class="container">
		<div class="row">
			<div class="aboutus-desc">
				<h1>About <em>HeyDay Technologies</em></h1>
				<p>
					<strong>HeyDay Technologies, </strong> started its journey some years ago from now.
					The founders of HeyDay Technologies always treated their clients like their friends and
					they not only provided them tech solutiuons but branding method as well..
				</p>
				<p>
					When <strong>HeyDay Technologies, </strong> was founded they saw a dream. A dream towards success and
					growth not only themselves but they wanted to work towards people's personal growth by their
					innovative ideas also.
				</p>
				<p>
					Often teams deliver only what is told without going beyond the given scope and with a lackadaisical attitude towards greater value creation.
					At <strong>HeyDay Technologies, </strong> we always try to bring something new and innovative for the people and society as well. We deliver something beyond of expectations always!
					For <strong>HeyDay Technologies, </strong> profit is not everything. They believe in long business
					relationship with their clients.
				</p>
			</div>
		</div>
	</div>
</section><!--about-middle end -->

app/views/homes/career.html.erb
<section class="main-career-page">

     <div class="careers-head"><!--sitemap-banner start -->
       <div class="container">
         <div class="row">
           <h1>Be a part of us! </h1>
           <p class="text-center">Let's begin your career with
             <em>
               HeyDay Technologies
             </em>
           </p>
         </div>
       </div>
     </div><!--sitemap-banner end -->

     <div class="career-content">
       <div class="container">
         <div class="row">
           <div class="quote-part">
             <blockquote>
               <p class="">
                 Find out what you like doing best, and get someone to pay you for it.
                 <footer><cite title="Source Title">Katharine Whitehorn</cite> </footer>
               </p>
             </blockquote>
           </div>
         </div>
         <div class="row open-position">
           <h3>We have some open positions</h3>
           <div class="col-md-6 col-sm-6 col-xs-12">
             <ul>
               <li>
                 <a href="#" data-toggle="modal" data-target="#myModal">
                   Trainee Developer
                 </a>
               </li>
               <li>
                 <a href="#" data-toggle="modal" data-target="#myModalROR">
                   Ruby on Rails Developer
                 </a>
               </li>
             </ul>
           </div>
           <div class="col-md-6 col-sm-6 col-xs-12">
             <p>
               Please share your resume at <strong><em>career@heydaytechnologies.com</em></strong>
             </p>
           </div>
         </div>
       </div>
     </div>

   
   </section> <!--main-career-page end -->


   <!-- Modal code start -->

   <!-- Modal -->
   <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="myModalLabel">Minimum Requirement for Trainee Developer</h4>
         </div>
         <div class="modal-body">
           <div class="row">
             <div class="col-md-6 col-sm-6 col-xs-12 job-desc">
               <p>Experience :</p>
               <p>Job Location :</p>
               <p>Qualification :</p>
               <br>
               <p>Skills :</p>
             </div>
             <div class="col-md-6 col-sm-6 col-xs-12 job-requirement">
               <p> 0-1 year</p>
               <p>Indore</p>
               <p>Graduation or Post graduation Degree in computer science branch.</p>
               <p> Object Oriented Methodologies and its features, JS, JQuery, Web Technology.</p>
             </div>
           </div>
           <div class="row">
             <p class="text-center resume-para">
               Please share your resume at <em>career@heydaytechnologies.com</em>
             </p>
           </div>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-started btn btn-warning" data-dismiss="modal">Close</button>
         </div>
       </div>
     </div>
   </div>

   <div class="modal fade" id="myModalROR" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="myModalLabel">Minimum Requirement for ROR Developer</h4>
         </div>
         <div class="modal-body">
           <div class="row">
             <div class="col-md-6 col-sm-6 col-xs-12 job-desc">
               <p>Experience :</p>
               <p>Job Location :</p>
               <p>Qualification :</p>
               <br>
               <p>Skills :</p>
             </div>
             <div class="col-md-6 col-sm-6 col-xs-12 job-requirement">
               <p> minimum 1+ year</p>
               <p>Indore</p>
               <p>Graduation or Post graduation Degree in computer science branch.</p>
               <p> Ruby and Rails framework with good communication skills, building web applications.</p>
             </div>
           </div>
           <div class="row">
             <p class="text-center resume-para">
               Please share your resume at <em>career@heydaytechnologies.com</em>
             </p>
           </div>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-started btn btn-warning" data-dismiss="modal">Close</button>
         </div>
       </div>
     </div>
   </div>

   <!--Modal code end -->

app/views/homes/index.html.erb
<section class="middle-section"><!--middle-section start -->
	<div class="container">
		<div class="row">
			<div class="type-wrap">
				<div id="typed-strings">
					<h1>Welcome at <strong>HeyDay Technologies</strong></h1>
					<h1>We turn dreams into reality</h1>
					<h1>People care about</h1>
					<p>Give us a chance!</p>
				</div>
				<span id="typed" style="white-space:pre;"></span>
			</div>

				<a href="#image"  class="btn btn-start tour">Let's start a tour!</a> 

		</div>
	</div>
</section><!--middle-section end -->

<section class="how-we-work-section" id="image"><!--how-we-work-section start -->
	<div class="container">
		<h1>
			How <strong>HeyDay Technologies</strong> work?
		</h1>
		<div class="row">
			<div class="how-we-work-img" >
				<img src="/assets/how-we-work.png" class="img-responsive center-block" alt="How we work">
			</div>
		</div>
	</div>
</section><!--how-we-work-section end -->

<section class="we-are-global-section"><!--we-are-global-section start -->
	<div class="container">
		<div class="row">
			<h1>
				<em>HeyDay Technologies</em>
				Is a global desgin and development consultancy platform.
			</h1>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<div class="icon">
					<i class="fa fa-cube fa-2x" aria-hidden="true"></i>
				</div>
				<p>Creative People</p>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<div class="icon">
					<i class="fa fa-connectdevelop fa-2x" aria-hidden="true"></i>
				</div>
				<p>Innovative Minds</p>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<div class="icon">
					<i class="fa fa-check-circle-o fa-2x"> </i>
				</div>
				<p>Quality</p>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<div class="icon">
					<i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
				</div>
				<p>Best Results</p>
			</div>
		</div>
	</div>
</section><!--we-are-global-section end -->

<section class="testimonial-section"><!--testimonial-section start -->
	<div class="container">
		<div class="row">
			<h2>Why people love us <i class="fa fa-smile-o" aria-hidden="true"></i></h2>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
					<li data-target="#carousel-example-generic" data-slide-to="2"></li>
				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<p>
							Very professional team and Quick communication, They are not only best engineers but a true firend also. They “Also helped me how I can brand my web app and what marketing strategies I should follow. I would give them 10 on 10.

							<span><strong>Mr. Jhon Mathew</strong> Social Network, Uk</span>
						</p>
					</div>
					<div class="item">
						<p>
							Very interesting team and very responsive, They are damn good. 
							I would recommend give them.
							They are so innovative and creative geeks.
							<br>
							<span><strong>Mr. A. H. Hameed</strong> Web App, UAE</span>
						</p>
					</div>
              
					<div class="item">
						<p>
							Awesome team and Quick communication, They helped me to build my Web App “Also helped me how I can brand my web app, Now My app has 60,000 Users, and I would love to recommend HeyDay Technologies Team.

							<span><strong>Mr. Gorge</strong>Social App, USA</span>
						</p>                
					</div>
				</div>           
			</div>
		</div>
	</div>
</section><!--testimonial-section end -->



<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script>
	$(function(){
		$("#typed").typed({
			stringsElement: $('#typed-strings'),
			typeSpeed: 100,
			backDelay: 500,
			loop: false,
			contentType: 'html', // or text
			// defaults to false for infinite loop
			loopCount: false,
			callback: function(){ foo(); },
			resetCallback: function() { newTyped(); }
		});

		$(".reset").click(function(){
			$("#typed").typed('reset');
		});
	});
	function newTyped(){ /* A new typed object */ }

	function foo(){ console.log("Callback"); }

	$(".tour").click(function() {
    $('html, body').animate({
      scrollTop: $("#image").offset().top
    }, 2000);
    event.preventDefault();
    event.stopPropagation();
   });
</script>

app/views/homes/services.html.erb
<section class="services-banner"><!--services-banner start -->
	<div class="container">
		<div class="row">
			<h1>
				<em>HeyDay Technologies</em> provide creative and innovative ideas
			</h1>
			<h3>When you need a dependable and professional team, look no further.</h3>
		</div>
	</div>
</section><!--services-banner end -->

<section class="services-content"><!--services-content start -->
	<div class="container">
		<div class="row">
			<h1>Our Specialities</h1>
		</div>
		<div class="row">
			<div class="col-sm-6">
				<div class="services-box right wow fadeInUp animated" data-wow-delay="0.5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
					<span class="services-icons fa fa-paper-plane animate"></span>
					<h3>Logo Design &amp; Branding</h3>
					<p>
						We have creative guys who can create your unique logo and make your brand
						unique and meaningfull.
						They are really innovative guys.
						They put their heart on their canvas and they are so imaginary too.
					</p>
				</div><!-- end servies-box -->
				<div class="services-box right wow fadeInUp animated" data-wow-delay="0.5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
					<span class="services-icons fa fa-apple animate"></span>
					<h3>Wordpress Themes</h3>
					<p>
						We can create wordpress themes and can work on them.
						We are specialists for that.
						We can provide you creative themes in less time.
						We have a team of specialists.
					</p>
				</div><!-- end servies-box -->
				<div class="services-box right wow fadeInUp animated" data-wow-delay="0.5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
					<span class="services-icons fa fa-street-view animate"></span>
					<h3>Startups ideas &amp; help</h3>
					<p>
						As a startup we know how to deal with a startup.
						We know how to help and what are the considerable points to the startups.
						We provide ideas too for the growing startups.
					</p>
				</div><!-- end servies-box -->
			</div>
			<div class="col-sm-6">
				<div class="services-box left wow fadeInUp animated" data-wow-delay="0.5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
					<span class="services-icons fa fa-laptop animate"></span>
					<h3>Mobile Development</h3>
					<p>
						We have an innovative team for the mobile app development.
						For them mobile app development is not just their task, but a fun for them.
						They can make your dream app real by their efforts.
					</p>
				</div><!-- end servies-box -->
				<div class="services-box left wow fadeInUp animated" data-wow-delay="0.5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
					<span class="services-icons fa fa-code animate"></span>
					<h3>Web Design &amp; Development</h3>
					<p>
						We have engineers who have great working experience in web app app development.
						We provide end to end solutions.
						We are specialists in web design and development.
					</p>
				</div><!-- end servies-box -->
				<div class="services-box left wow fadeInUp animated" data-wow-delay="0.5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
					<span class="services-icons fa fa-smile-o animate"></span>
					<h3>Client Support</h3>
					<p>
						We provide 24x7 (almost) hours support to our clients.
					</p>
				</div><!-- end servies-box -->
			</div>
		</div>
	</div>
</section><!--services-content end -->

app/views/homes/sitemap.html.erb
<section class="sitemap-banner"><!--sitemap-banner start -->
<div class="container">
  <div class="row">
    <h1>Sitemap </h1>
  </div>
</div>
</section><!--sitemap-banner end -->

<section class="sitemap-content">
<div class="container">
  <div class="row">
    <div class="block-content">
      <div class="block-content-texts">
        <h2>Sitemap content</h2>

        <p>Here is an overview of the Site Map :</p>

        <ul>
          <li>The Homepage :&nbsp;<%= link_to 'HeyDay Technologies.com', '/' %></li>
          <li>The Presentation of the HeyDay Technologies :&nbsp;
            <%= link_to 'HeyDay Technologies.com/aboutUs', '/aboutUs' %>
          </li>
          <li>The list of all the services by HeyDay Technologies :&nbsp;<%= link_to 'HeyDay Technologies.com/services', '/services' %></li>
          <li>HeyDay Technologies news and events :&nbsp;<a href="HeyDay Technologies.com/news">HeyDay Technologies.com/hts-channel</a></li>
          <li>The contact page :&nbsp;<%= link_to 'HeyDay Technologies.com/contact', '/contact' %></li>
          <li>The application page :&nbsp;<a href="HeyDay Technologies.com/let's-connect">HeyDay Technologies.com/let's-connect</a></li>
          <li>Our portfolio :&nbsp;<%= link_to 'HeyDay Technologies.com/works', '/work'%></li>
          <li>The press release page :&nbsp;<a href="HeyDay Technologies.com/hts-channel">HeyDay Technologies.com/hts-channel</a></li>
          <li>How HeyDay Technologies :&nbsp;<%= link_to 'HeyDay Technologies.com/services', '/services' %></li>
          <li>The Career page :&nbsp;<%= link_to 'HeyDay Technologies.com/careers', '/career' %></li>
          <li>The Blog page :&nbsp;<%= link_to 'HeyDay Technologies.com/blog', '/posts' %> </li>
        </ul>

        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>
</section>

app/views/homes/work.html.erb
<section class="our-work-banner"><!--our-work-banner start -->
	<div class="container">
		<div class="row">
			<h1>
				<em>HeyDay Technologies</em> provide great solutions 
			</h1>
			<h3>We have worked on so many projects</h3>
		</div>
	</div>
</section><!--our-work-banner end -->

<section class="our-work-content"><!--our-work-content start -->
	<div class="container">
		<div class="row">
			<h1 class="text-center">Our Recent Creation</h1>
			<div class="col-md-6 col-sm-6 col-xs-12 our-work-content-left">
				<div class="project-discussion">
					<img src="assets/lucre.jpg" class="center-block img-responsive" alt="HeyDay Technologies Project">
					<a class="project-title services-link" href="http://lgfresearch.com/">
						LgfResearch.com
					</a>
					<p class="project-desc">
						Lucre Global is an market share and financiary advisary web app.
						In this app we implemented so many great features.
						In this we have added paypal and social media plugins.
					</p>
				</div>
				<div class="project-discussion">
					<img src="assets/portugalux.jpg" class="center-block img-responsive" alt="HeyDay Technologies Project">
					<a class="project-title services-link" href="http://portugalux.com/">
						portugalux.com
					</a>
					<p class="project-desc">
						This is hotel and tourism  booking  system in which user can book seasonal and vocational holiday , can get  coupon discount etc.
						having a vast admin panel , can manage everything from there like property, featured , discount, social management , user management , reports etc.
					</p>
				</div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12 our-work-content-right">
				<div class="project-discussion">
					<img src="assets/offerwalebabu.jpg" class="center-block img-responsive" alt="HeyDay Technologies Project">
					<a class="project-title services-link" href="http://offerwalebabu.in/">
						OfferWaleBabu
					</a>
					<p class="project-desc">
						Offer Wale Babu is developed and designed by HeyDay Technologies.
						In this we have implemented so many latest features.
						Offer Wale Babu is a platform to check hot offers and deals with your rates.
						We are working towards AI for this.
					</p>
				</div>
				<div class="project-discussion">
					<img src="assets/directdienst_netsimpel.jpg" class="center-block img-responsive" alt="HeyDay Technologies Project">
					<a class="project-title services-link" href="http://directdienst.netsimpel.com/workora/">
						directdienst.netsimpel.com
					</a>
					<p class="project-desc">
						this is job portal made in laravel framework . simply logic behind this project is a needed end user will post a job according to their requirement and company or individual belonging to this  job category and apply on the job.
					</p>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</section><!--our-work-content end -->

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-8">
      <!-- Title -->
      <h1 class="blog-head"><%= @post.title.titleize %></h1>
      <!-- Author -->
      <hr>
      <!-- Date/Time -->
      <b>Posted on <%= @post.published_at.strftime("%d %B %Y") %><br></b>
      <hr>
      <div class="img-fluid rounded">
        <%= image_tag(@post.banner_image, :alt => "Picture", class: "center-block img-responsive") %>
      </div>
      <br>
      <hr>
      <!-- Post Content -->
      <%= @post.description.html_safe %>
      <%= social_share_button_tag(@post.title, :url => post_url(@post), description: @post.title) %>
      <!-- Single Comment -->
      <div class="card my-4">
        <div class="card-body">
          <%= render 'comments/form' %>
        </div>
      </div>
    </div>
    <div class="col-md-4 ">
     <!-- Categories Widget -->
      <div class="card my-4 recentpost">
        <h3 class="card-header">Recent Post</h3>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <%= render 'posts/recent_post' %>
                </li>               
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- Side Widget -->
      <div class="card my-4">
        <h5 >Recent Comments:</h5>
        <% @post.comments.recent_comment.each do |post_cmnt| %>
        <h5><%= post_cmnt.name %></h5>
        <%= post_cmnt.message %>
        <% end %>
      </div>
    </div>
  </div>
</div>